# Generated by Django 5.2.5 on 2025-08-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('material_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255, unique=True)),
                ('unit_of_measurement', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.materialcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateMaterialItem',
            fields=[
                ('item_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estimateitem')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.project'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='PriceChangeRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estimateitem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='api.user')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimates', to='api.user'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_estimates', to='api.user'),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('work_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_name', models.CharField(max_length=255, unique=True)),
                ('unit_of_measurement', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.worktype')),
            ],
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.worktype'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='WorkMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.materialtype')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.worktype')),
            ],
            options={
                'unique_together': {('work_type', 'material_type')},
            },
        ),
    ]
