# Generated by Django 5.2.5 on 2025-08-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_status_alter_estimate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_estimates', to='api.user'),
        ),
    ]
