# Generated by Django 5.2.5 on 2025-08-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_estimate_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Счетчик использования для определения популярных работ'),
        ),
    ]
