# Generated by Django 5.2.5 on 2025-08-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_worktype_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='added_estimate_items', to='api.user'),
        ),
    ]
