# Generated by Django 5.2.5 on 2025-08-24 10:08

from django.db import migrations


def populate_added_by(apps, schema_editor):
    """
    Заполняет поле added_by для существующих EstimateItem.
    Логика: added_by = foreman сметы (тот кто создал смету)
    """
    EstimateItem = apps.get_model('api', 'EstimateItem')
    
    estimate_items = EstimateItem.objects.select_related('estimate__foreman').all()
    
    for item in estimate_items:
        if item.estimate.foreman:
            item.added_by = item.estimate.foreman
            item.save()


def reverse_populate_added_by(apps, schema_editor):
    """
    Откат миграции - очищает поле added_by
    """
    EstimateItem = apps.get_model('api', 'EstimateItem')
    EstimateItem.objects.all().update(added_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_added_by_to_estimate_item'),
    ]

    operations = [
        migrations.RunPython(populate_added_by, reverse_populate_added_by),
    ]
