version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-estimate
    environment:
      POSTGRES_DB: estimate_app_db
      POSTGRES_USER: estimate_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U estimate_user -d estimate_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - estimate_network

  # Опциональный pgAdmin для управления базой данных
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-estimate
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@estimate.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - estimate_network
    profiles:
      - tools  # Запускается только с профилем --profile tools

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  estimate_network:
    driver: bridge