name: ⚡ Quick Deploy (Code Changes Only)

on:
  # push:
  #   branches:
  #     - dev  # ОТКЛЮЧЕНО - теперь используется deploy-dev.yml
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Тип деплоя'
        required: true
        default: 'code-only'
        type: choice
        options:
          - code-only
          - backend-only
          - migrations-only

env:
  SERVER_HOST: 195.14.122.135
  SERVER_USER: root
  PROJECT_PATH: /var/www/estimate-app

jobs:
  quick-deploy:
    name: ⚡ Quick Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Нужно для сравнения изменений

      - name: 🔑 Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_SSH_KEY }}

      - name: 📋 Analyze changes
        id: changes
        run: |
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
          
          # Определяем тип изменений
          if git diff --name-only HEAD~1 HEAD | grep -E '\.py$'; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          fi
          
          if git diff --name-only HEAD~1 HEAD | grep -E '\.(js|jsx|ts|tsx)$'; then
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          fi
          
          if git diff --name-only HEAD~1 HEAD | grep migrations; then
            echo "migrations_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: ⚡ Deploy code changes
        run: |
          # Копируем скрипт быстрого деплоя
          scp deploy/quick-deploy.sh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.PROJECT_PATH }}/
          
          # Выполняем быстрый деплой
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.PROJECT_PATH }} && bash quick-deploy.sh ${{ github.sha }}"

      - name: 🏗️ Rebuild frontend (if needed)
        if: steps.changes.outputs.frontend_changed == 'true'
        run: |
          echo "⚠️ Frontend изменился - требуется полная пересборка"
          echo "Запустите полный деплой для обновления frontend"

      - name: ✅ Quick deployment success
        run: |
          echo "⚡ Быстрый деплой завершен!"
          echo "🌐 Приложение доступно на: http://app.iqbs.pro"
          if [ "${{ steps.changes.outputs.frontend_changed }}" == "true" ]; then
            echo "⚠️ Для frontend изменений требуется полный деплой"
          fi